check-leaks: true
color: true
extension:
  - 'js'
file:
  - './test/mixins/GenerateUuidIdMixin-test.js'
  # - './test/mixins/HttpSerializerMixin-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
# require: '@babel/register'
require: 'register-babel.js'
# spec: 'test/**/**/*-test.js'
watch: false
