check-leaks: true
color: true
extension:
  - 'js'
file:
  # - './test/transforms/ArrayTransform-test.js'
  # - './test/transforms/BooleanTransform-test.js'
  # - './test/transforms/DateTransform-test.js'
  # - './test/transforms/NumberTransform-test.js'
  # - './test/transforms/ObjectTransform-test.js'
  # - './test/transforms/StringTransform-test.js'
  # - './test/mapper/Cursor-test.js'
  # - './test/mapper/Objectizer-test.js'
  # - './test/mapper/Transform-test.js'
  # - './test/mapper/Serializer-test.js'
  # - './test/mapper/Record-test.js'
  # - './test/mapper/Migration-test.js'
  # - './test/mixins/GenerateUuidIdMixin-test.js'
  # - './test/mixins/IterableMixin-test.js'
  # - './test/mixins/HttpAdapterMixin-test.js'
  # - './test/mixins/RelationsMixin-test.js'
  # - './test/mixins/MemoryMigrationMixin-test.js'
  # - './test/mixins/SchemaModuleMixin-test.js' # TODO: needs corrections in SchemaModuleMixin
  # - './test/proxies/Collection-test.js'
  - './test/decorators/attribute-test.js'
  - './test/decorators/computed-test.js'
  # - './test/commands/MigrateCommand-test.js'
  # - './test/commands/RollbackCommand-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
# require: '@babel/register'
require: 'register-babel.js'
# spec: 'test/**/**/*-test.js'
watch: false
